{% set name = "redoxcalc" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/GES-compchem/{{ name }}/archive/refs/tags/{{ version }}.zip

build:
  noarch: python
  number: 0

requirements:
  host:
    - python>=3.8
  run:
    - python>=3.8
    - rdkit
    - jobdispatcher
    - pickle

about:
  license: UNKNOWN
  license_family: OTHER
  license_file:
  summary: ""
  doc_url:
  dev_url:

extra:
  recipe-maintainers:
    - GES-compchem